langs = {
    'en': {
        'authorization': 'Authorization was successful',
        'registration': 'To register, share your Contact',
        'contact': 'Share contact',
        'reg_complete': 'Registration was successfully',

        'start_order': '🛍 Start order',
        'history_order': '📓 History of orders',
        'cart': '🛒 Cart',
        'settings': '⚙ Settings',
        'support': '☎ Tech support',

        'sel_category': 'Choose category',
        'location': 'To continue ordering, please send your location',
        'my_addresses': '🗺 My addresses',
        'send_location': '📌 Send location',
        'back': '⬅ Back',
        'yes': '✅ Yes',
        'no': '❌ No',
        'no_location': 'You dont have any saved addresses',
        'choose_address': 'Select delivery address',
        'address_selected': 'Address selected',
        'address_saved': 'Address saved',

        'product': 'Choose product: ',
        'description': 'Description',
        'author': 'Author',
        'price': 'Price',
        'zero': 'You cant go below zero',
        'added_to_cart': 'Product added successfully',
        'add_to_cart': '📥 Add to cart',
        'change_quantity': 'Product quantity changed',

        'no_cart': 'Cart is not available. Contact technical support',
        'in_cart': '🛒 In cart',
        'quantity': 'Quantity',
        'total_cost': 'Total cost',
        'total_products': 'Total quantity of products',
        'total': 'Total',
        'delivery': 'Delivery',
        'currency': 'sum',
        'number_order': 'Order №',

        'delete_product': 'Product successfully removed from the cart',
        'no_products': 'Add products to the cart first',
        'type_payment': 'Choose a payment method: ',
        'make_order': '🚖 Place an order',
        'delete_cart': '🗑 Clear the entire cart',
        'empty_cart': 'The cart is empty',
        'clean_cart': 'All items removed from the cart',
        'cash': '💵 Cash',
        'order_placed': 'Order placed',
        'error_payment': 'Error, payment failed!',
        'payment_success': 'Payment successful. Expect your order',

        'choose_option': 'Choose option',
        'change_lang': 'Change language',
        'select_lang': 'Select language',
        'contact_support': 'Tech support',
        'message_support': 'We are sorry that you are having difficulties. Let tech support know about your problem.',

        'hello_admin': 'Welcome to the admin panel. To exit this mode, enter the /start command',
        'change_menu': '🔧 Change menu',
        'statistics': '📊 Statistics',
        'change_category': 'Select a category or add a new one',
        'create_new': '📝 Add a category',
        'new_name': 'Enter the name of the new category separated by forward slash, '
                    'in a strict format, first in Russian then in English. For example Категория/Сategory',
        'change_product': 'Select a product to modify or add a new one:',
        'add_new_prod': '✅ Add product ✅',
        'delete_category': '❌ Delete this category ❌',
        'delete_book': 'The book was successfully deleted',
        'removed_category': 'The category and all products in it were successfully deleted',
        'create_new_prod': "Let's create a new product. Enter the name of the new book on russian",
        'create_new_prod_en': "Enter the name of the new book on english",
        'ask_author': 'Great! Now send me the author of this book on russian',
        'ask_author_en': 'Now send me the author of this book on english',
        'ask_price': 'Excellent. Now enter the price for the new book',
        'ask_description': 'Okay. Next, I need a description of the new book on russian',
        'ask_description_en': 'Next, I need a description of the new book on english',
        'check_price': 'The price must be a number. Please enter a valid value.',
        'ask_image': 'Wonderful. Send me a photo of the new book',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'not_save': 'The product was not saved',
        'destroy_book': '🗑 Delete book',
        'one_month': '1️⃣ month',
        'three_month': '3️⃣ months',
        'six_month': '6️⃣ months',
        'twelve_month': '1️⃣2️⃣ months',
        'period_stat': 'Select a period to display statistics',
    },
    'ru': {
        'authorization': 'Авторизация прошла успешно',
        'registration': 'Для регистрации поделитесь Контактом',
        'contact': 'Поделится контактом',
        'reg_complete': 'Регистрация прошла успешно',

        'start_order': '🛍 Начать заказ',
        'history_order': '📓 История заказов',
        'cart': '🛒 Корзина',
        'settings': '⚙ Настройки',
        'support': '☎ Тех поддержка',

        'sel_category': 'Выберите категорию',
        'location': 'Чтобы продолжить заказ, отправьте вашу локацию',
        'my_addresses': '🗺 Мои адреса',
        'send_location': '📌 Отправить локацию',
        'back': '⬅ Назад',
        'yes': '✅ Да',
        'no': '❌ Нет',
        'no_location': 'У вас еще нет сохраненных адресов',
        'choose_address': 'Выберите адрес доставки',
        'address_selected': 'Адрес выбран',
        'address_saved': 'Адрес записан',

        'product': 'Выберите товар: ',
        'description': 'Описание',
        'author': 'Автор',
        'price': 'Цена',
        'zero': 'Ниже нуля нельзя',
        'added_to_cart': 'Товар успешно добавлен',
        'add_to_cart': '📥 Добавить в корзину',
        'change_quantity': 'Количество товара изменено',

        'no_cart': 'Корзина не доступна. Обратитесь в тех поддержку',
        'in_cart': '🛒 В корзине',
        'quantity': 'Количество',
        'total_cost': 'Общая стоимость',
        'total_products': 'Общее количество товаров',
        'total': 'Итоговая стоимость',
        'delivery': 'Доставка',
        'currency': 'сум',
        'number_order': 'Заказ №',

        'delete_product': 'Товар успешно удален из корзины',
        'no_products': 'Сначала добавьте товары в корзину',
        'type_payment': 'Выберите способ оплаты: ',
        'make_order': '🚖 Оформить заказ',
        'delete_cart': '🗑 Очистить всю корзину',
        'empty_cart': 'Корзина пуста',
        'clean_cart': 'Все товары из корзины удалены',
        'cash': '💵 Наличные',
        'order_placed': 'Заказ оформлен',
        'error_payment': 'Ошибка, оплата не прошла!',
        'payment_success': 'Оплата прошла успешна. Ожидайте свой заказ',

        'choose_option': 'Выберите опцию',
        'change_lang': 'Сменить язык',
        'select_lang': 'Выберите язык',
        'contact_support': 'Тех поддержка',
        'message_support': 'Нам жаль что у вас возникли трудности. Сообщите тех поддержке о своей проблеме.',

        'hello_admin': 'Добро пожаловать в админ панель, чтобы выйти из этого режима введите команду /start',
        'change_menu': '🔧 Изменить меню',
        'statistics': '📊 Статистика',
        'change_category': 'Выберите категорию или добавьте новую',
        'create_new': '📝 Добавить категорию',
        'new_name': 'Введите название новой категории через слеш в строгом формате сначала на русском, '
                    'затем на английском языке. Например: Категория/Category',
        'change_product': 'Выберите товар для изменения или добавления нового: ',
        'add_new_prod': '✅ Добавить продукт ✅',
        'delete_category': '❌ Удалить данную категорию ❌',
        'delete_book': 'Книга успешно удалена',
        'removed_category': 'Категория и все товары в ней успешно удалены',
        'create_new_prod': 'Давайте создадим новый товар. Введите название новой книги на русском',
        'create_new_prod_en': 'Введите название новой книги на английском',
        'ask_author': 'Супер! Теперь отправьте мне автора данной книги на русском',
        'ask_author_en': 'Теперь отправьте мне автора данной книги на английском',
        'ask_price': 'Отлично. Теперь введите цену на новую книгу',
        'ask_description': 'Хорошо. Далее мне нужно описание новой книги на русском',
        'ask_description_en': 'Далее мне нужно описание новой книги на английском',
        'check_price': 'Цена должна быть числом. Пожалуйста, введите корректное значение.',
        'ask_image': 'Замечательно. Отправьте мне фото новой книги',
        'confirm': 'Подтвердить',
        'cancel': 'Отмена',
        'not_save': 'Товар не сохранен',
        'destroy_book': '🗑 Удалить книгу',
        'one_month': '1️⃣ месяц',
        'three_month': '3️⃣ месяца',
        'six_month': '6️⃣ месяцев',
        'twelve_month': '1️⃣2️⃣ месяцев',
        'period_stat': 'Выберите период для вывода статистики',
    }
}
